//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonoagente
    {
        public int index { get; set; }
        public string Folio { get; set; }
        public string Cliente { get; set; }
        public double Total { get; set; }
        public double saldo { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
