//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentesventa
    {
        public int index { get; set; }
        public string nombre { get; set; }
        public string RFC { get; set; }
        public string Curp { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public string poblacion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public double porcentaje { get; set; }
        public double limite { get; set; }
        public string plazoC { get; set; }
        public string Estado { get; set; }
        public string radio { get; set; }
        public string movil { get; set; }
        public string nombre_compl { get; set; }
    }
}
