//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacen_av_pvf
    {
        public int id_agente_venta { get; set; }
        public string modelo { get; set; }
        public string codigob { get; set; }
        public int inicial { get; set; }
        public int exist { get; set; }
        public System.DateTime fecha { get; set; }
        public int traspaso { get; set; }
        public int traspasado { get; set; }
        public int pzasxpaq { get; set; }
    }
}
