//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacen_modelo
    {
        public int idalmacen { get; set; }
        public string modelo { get; set; }
        public string descripcion { get; set; }
        public int inicial { get; set; }
        public int existencia { get; set; }
        public int entrada { get; set; }
        public int salida { get; set; }
        public int final { get; set; }
        public System.DateTime fecha { get; set; }
        public int diferencia { get; set; }
    }
}
