//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacene
    {
        public int idalmacenes { get; set; }
        public string modelo { get; set; }
        public int nopiezas { get; set; }
        public int faltante { get; set; }
        public int corte { get; set; }
        public string observacion { get; set; }
        public int entrada { get; set; }
        public int salida { get; set; }
        public bool devolucion { get; set; }
        public string lavanderia { get; set; }
    }
}
