//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_av_pvf
    {
        public int id_asigavpv { get; set; }
        public int noclientes { get; set; }
        public int pzaspromv { get; set; }
        public int paqpromv { get; set; }
        public double porcentaje { get; set; }
        public int id_agente_venta { get; set; }
    }
}
