//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogomp
    {
        public int indexmp { get; set; }
        public string codigob { get; set; }
        public string modelo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int idproveedor { get; set; }
        public double existencia { get; set; }
        public double apartado { get; set; }
        public double costoh { get; set; }
        public double costop { get; set; }
        public double coston { get; set; }
        public int pzasxemp { get; set; }
        public string infoboton { get; set; }
        public int iddepartamento { get; set; }
        public int idacabado { get; set; }
        public double min { get; set; }
        public double max { get; set; }
        public double medida { get; set; }
        public string unidadm { get; set; }
        public string color { get; set; }
        public int foto1 { get; set; }
        public int foto2 { get; set; }
        public int foto3 { get; set; }
    }
}
