//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente1
    {
        public int idcliente { get; set; }
        public string cliente { get; set; }
        public string direccionf { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
        public string poblacion { get; set; }
        public string estado { get; set; }
        public double limite { get; set; }
        public double saldo { get; set; }
        public string rfc { get; set; }
        public string telefono { get; set; }
        public string direccione { get; set; }
        public string contacto { get; set; }
        public string email { get; set; }
        public string agente { get; set; }
        public string plazo { get; set; }
        public string lp { get; set; }
        public string abreviado { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public string referencia { get; set; }
        public string municipio { get; set; }
        public string pais { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_cliente { get; set; }
        public int idClasif { get; set; }
        public string NumDeCuenta { get; set; }
        public string status { get; set; }
        public double descuento { get; set; }
    }
}
