//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_pedidospvf
    {
        public int id_folio { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_cliente { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public int id_agente_venta { get; set; }
        public string factrem { get; set; }
        public double total { get; set; }
        public string cantletra { get; set; }
        public int nopzas { get; set; }
        public int nopaq { get; set; }
        public System.DateTime fechav1 { get; set; }
        public double totalv1 { get; set; }
        public System.DateTime fechav2 { get; set; }
        public double totalv2 { get; set; }
        public System.DateTime fechav3 { get; set; }
        public double totalv3 { get; set; }
        public string direnvio { get; set; }
        public string observacion { get; set; }
        public bool eliminar { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string status { get; set; }
    }
}
