//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_osmph
    {
        public int idosmph { get; set; }
        public string modelo { get; set; }
        public double canthabilitada { get; set; }
        public System.DateTime fecha { get; set; }
        public string maquila { get; set; }
        public double etiquetap1 { get; set; }
        public double etiquetap2 { get; set; }
        public double etiquetapt { get; set; }
        public double costototal { get; set; }
        public bool devolucion { get; set; }
        public double cantidadtotal { get; set; }
        public string codigob { get; set; }
        public int factprop { get; set; }
    }
}
