//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conentrada
    {
        public int index { get; set; }
        public string folio { get; set; }
        public string nopiezas { get; set; }
        public string nopaq { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string Nomodelos { get; set; }
        public string almacen { get; set; }
        public string saldos { get; set; }
        public string Empleado { get; set; }
        public string lavanderia { get; set; }
        public bool devolucion { get; set; }
    }
}
