//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conentrada_almacen
    {
        public int idea { get; set; }
        public System.DateTime fecha { get; set; }
        public int idproveedor { get; set; }
        public string plazocredito { get; set; }
        public int nopzas { get; set; }
        public double total { get; set; }
        public string foliooea { get; set; }
        public string foliooc1 { get; set; }
        public string foliooc2 { get; set; }
        public string foliooc3 { get; set; }
        public string foliooc4 { get; set; }
        public string foliooc5 { get; set; }
        public string foliofr1 { get; set; }
        public string foliofr2 { get; set; }
        public string foliofr3 { get; set; }
        public string foliofr4 { get; set; }
        public string foliofr5 { get; set; }
        public string observacion { get; set; }
        public string condicion { get; set; }
        public bool devolucion { get; set; }
    }
}
