//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confactura_electronica
    {
        public int idfe { get; set; }
        public int idcliente { get; set; }
        public int idempresa { get; set; }
        public string tipo_doc { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string forma_pago { get; set; }
        public string lugar_exped { get; set; }
        public string metodo_pago { get; set; }
        public string no_cuenta { get; set; }
        public string path_xml { get; set; }
        public double subtotal { get; set; }
        public double subtotal_desc { get; set; }
        public double impuesto { get; set; }
        public double descuento { get; set; }
        public string motivo_desc { get; set; }
        public double total { get; set; }
        public string cant_letra { get; set; }
        public bool eliminar { get; set; }
        public bool timbrado { get; set; }
        public bool cancelado { get; set; }
        public string uuid { get; set; }
        public string plazo { get; set; }
        public int folio { get; set; }
        public int estado { get; set; }
        public string direccionEnvio { get; set; }
        public string observaciones { get; set; }
    }
}
