//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class connotacredito
    {
        public int Index { get; set; }
        public string FolioNC { get; set; }
        public string FolioFR { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cliente { get; set; }
        public double Total { get; set; }
        public string Tipo { get; set; }
        public string Letra { get; set; }
        public double Subtotal { get; set; }
        public double Iva { get; set; }
        public string Poblacion { get; set; }
        public int NoPzas { get; set; }
        public int NoPaq { get; set; }
        public string folio1 { get; set; }
        public string folio2 { get; set; }
        public string folio3 { get; set; }
        public string os1 { get; set; }
        public string os2 { get; set; }
        public string os3 { get; set; }
        public System.DateTime c1 { get; set; }
        public System.DateTime c2 { get; set; }
        public System.DateTime c3 { get; set; }
        public string Observacion1 { get; set; }
        public string Observacion2 { get; set; }
        public string Observacion3 { get; set; }
        public bool devolucion { get; set; }
    }
}
