//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conorden_salida
    {
        public int indexfolio { get; set; }
        public string foliofact { get; set; }
        public string folio { get; set; }
        public string foliodocto { get; set; }
        public System.DateTime fecha { get; set; }
        public string cliente { get; set; }
        public string cs { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public string vendedor { get; set; }
        public string paqueteria { get; set; }
        public string noguia { get; set; }
        public string noguia1 { get; set; }
        public string fact_rem { get; set; }
        public double total { get; set; }
        public string letra { get; set; }
        public int nopzas { get; set; }
        public int nopaq { get; set; }
        public bool eliminar { get; set; }
        public double Genvio { get; set; }
        public double TotalGE { get; set; }
        public double Saldo { get; set; }
        public double Abono { get; set; }
        public string DiasC { get; set; }
        public System.DateTime FechaV { get; set; }
        public string almacen { get; set; }
        public string observacion { get; set; }
    }
}
