//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conorden_compra
    {
        public int idoc { get; set; }
        public System.DateTime fecha { get; set; }
        public int idproveedor { get; set; }
        public string deptosol { get; set; }
        public int nopzas { get; set; }
        public double total { get; set; }
        public string foliooc { get; set; }
        public string foliop1 { get; set; }
        public string foliop2 { get; set; }
        public string foliop3 { get; set; }
        public string foliop4 { get; set; }
        public System.DateTime fechae1 { get; set; }
        public System.DateTime fechae2 { get; set; }
        public System.DateTime fechae3 { get; set; }
        public System.DateTime fechae4 { get; set; }
        public string observacion { get; set; }
        public bool surtida { get; set; }
        public bool devolucion { get; set; }
    }
}
