//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conos_conpvf
    {
        public int id { get; set; }
        public int id_relacion { get; set; }
        public int indexfolio { get; set; }
        public int id_folio { get; set; }
        public int id_remision { get; set; }
    }
}
