//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conpedido
    {
        public int folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
        public double TotalSurtido { get; set; }
        public int SNopaq { get; set; }
        public int SNopzas { get; set; }
        public int Nopaq { get; set; }
        public int NoPzas { get; set; }
        public string cantidadletra { get; set; }
        public string cliente { get; set; }
        public string poblacion { get; set; }
        public string direccion { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string telefono { get; set; }
        public bool eliminar { get; set; }
        public string estado { get; set; }
        public int idcliente { get; set; }
        public int idusuario { get; set; }
    }
}
