//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conrecibo
    {
        public int idrecibo { get; set; }
        public string movimiento { get; set; }
        public string norefmov { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int idcliente { get; set; }
        public string concepto { get; set; }
        public string observacion { get; set; }
        public int idos { get; set; }
        public string folioremfact { get; set; }
        public int idabono { get; set; }
        public double total { get; set; }
        public bool devolucion { get; set; }
        public int folio { get; set; }
    }
}
