//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conventa
    {
        public int index { get; set; }
        public string folio { get; set; }
        public System.DateTime fecha { get; set; }
        public int cliente { get; set; }
        public string ciudad { get; set; }
        public string tipo { get; set; }
        public double Abono { get; set; }
        public double Saldo { get; set; }
        public string estado { get; set; }
        public double total { get; set; }
        public int nopzas { get; set; }
        public int nopaq { get; set; }
        public bool eliminar { get; set; }
    }
}
