//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class corridas_produccion
    {
        public string codigob { get; set; }
        public string modelo { get; set; }
        public int AA { get; set; }
        public int AB { get; set; }
        public int AT { get; set; }
        public int BA { get; set; }
        public int BB { get; set; }
        public int BT { get; set; }
        public int CA { get; set; }
        public int CB { get; set; }
        public int CT { get; set; }
        public int DA { get; set; }
        public int DB { get; set; }
        public int DT { get; set; }
        public int EA { get; set; }
        public int EB { get; set; }
        public int ET { get; set; }
        public int FA { get; set; }
        public int FB { get; set; }
        public int FT { get; set; }
        public int GA { get; set; }
        public int GB { get; set; }
        public int GT { get; set; }
        public int HA { get; set; }
        public int HB { get; set; }
        public int HT { get; set; }
        public int IA { get; set; }
        public int IB { get; set; }
        public int IT { get; set; }
        public int TA { get; set; }
        public int TB { get; set; }
        public int TT { get; set; }
    }
}
