//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dellatedeposito
    {
        public int Index { get; set; }
        public string Indexfolio { get; set; }
        public string FolioOS { get; set; }
        public string Banco { get; set; }
        public string Beneficiario { get; set; }
        public string NoCta { get; set; }
        public double Importe { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool eliminar { get; set; }
    }
}
