//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecheque1
    {
        public int Index { get; set; }
        public string Indexfolio { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaC { get; set; }
        public System.DateTime FechaRC { get; set; }
        public string Banco { get; set; }
        public string Titular { get; set; }
        public string NoCheque { get; set; }
        public string Status { get; set; }
        public double Importe { get; set; }
        public string Documentado { get; set; }
        public int Eliminar { get; set; }
    }
}
