//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int idempresa { get; set; }
        public string nombre_empresa { get; set; }
        public string nombre_fiscal { get; set; }
        public string rfc { get; set; }
        public string telefono { get; set; }
        public string pais { get; set; }
        public string calle { get; set; }
        public string no_exterior { get; set; }
        public string no_interior { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string referencia { get; set; }
        public string cp { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string regimen_fiscal { get; set; }
        public string archivo_cer { get; set; }
        public string archivo_key { get; set; }
        public string password_llave { get; set; }
        public string caducidad_certificado { get; set; }
        public string no_serie { get; set; }
        public string cbb { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string servidor { get; set; }
        public int puerto { get; set; }
        public string email { get; set; }
        public string password_email { get; set; }
        public string registroPatronal { get; set; }
        public string curp { get; set; }
        public string claveEntidad { get; set; }
    }
}
