//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        public string folio { get; set; }
        public string codigob { get; set; }
        public string modelo { get; set; }
        public string nopaq { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string nopiezas { get; set; }
        public string descripcion { get; set; }
        public string almacen { get; set; }
        public string saldo { get; set; }
        public string loteproduccion { get; set; }
        public string observacion { get; set; }
        public bool devolucion { get; set; }
        public string corte { get; set; }
    }
}
