//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_electronica
    {
        public int idfe { get; set; }
        public int cantidad { get; set; }
        public int pzas_paq { get; set; }
        public int pzas_total { get; set; }
        public string codigob { get; set; }
        public string descripcion { get; set; }
        public string unidad { get; set; }
        public double preciociva { get; set; }
        public double totalciva { get; set; }
        public double preciosiva { get; set; }
        public double totalsiva { get; set; }
        public bool eliminar { get; set; }
    }
}
