//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kardexpvf
    {
        public int id_kardex { get; set; }
        public string codigob { get; set; }
        public string modelo { get; set; }
        public System.DateTime fecha { get; set; }
        public string movimiento { get; set; }
        public string folio { get; set; }
        public int cantidad { get; set; }
        public int id_agente_venta { get; set; }
        public int existenciaini { get; set; }
        public int existenciafin { get; set; }
    }
}
