//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mp
    {
        public int idmp { get; set; }
        public string depto { get; set; }
        public string nombre { get; set; }
        public string comcalmed { get; set; }
        public string codcolmod { get; set; }
        public string color { get; set; }
        public string acabado { get; set; }
        public string presentacion { get; set; }
        public double anchocant { get; set; }
        public string um { get; set; }
        public double preciosiva { get; set; }
        public double preciociva { get; set; }
        public string observacion { get; set; }
        public string ubicacion { get; set; }
        public string localizacion { get; set; }
        public double existcue { get; set; }
        public double existpue { get; set; }
        public double coston { get; set; }
        public double costop { get; set; }
        public double costoh { get; set; }
        public double min { get; set; }
        public double max { get; set; }
        public string codigob { get; set; }
        public string codigob2 { get; set; }
        public int idfoto { get; set; }
        public int idproveedor { get; set; }
        public int idfamilia { get; set; }
        public double transitocue { get; set; }
        public double transitopue { get; set; }
        public bool servicioactivo { get; set; }
        public bool lotes { get; set; }
    }
}
