//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notacredito
    {
        public string Index { get; set; }
        public System.DateTime Fecha { get; set; }
        public int cantidad { get; set; }
        public string Modelo { get; set; }
        public double precio { get; set; }
        public string CodigoBarra { get; set; }
        public int nopzas { get; set; }
        public string Descripcion { get; set; }
        public double Total { get; set; }
        public string Tipo { get; set; }
        public bool devolucion { get; set; }
    }
}
