//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_compra
    {
        public int idoc { get; set; }
        public string codigob { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public double medida { get; set; }
        public string unidadm { get; set; }
        public string color { get; set; }
        public double coston { get; set; }
        public double importe { get; set; }
        public System.DateTime fecha { get; set; }
        public int nopzas { get; set; }
        public int surtido { get; set; }
        public bool devolucion { get; set; }
    }
}
