//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osmpa
    {
        public int idosmpa { get; set; }
        public int idproveedor { get; set; }
        public int indexmp { get; set; }
        public string descripcion { get; set; }
        public double cantidad { get; set; }
        public double costo { get; set; }
        public double total { get; set; }
        public string observacion { get; set; }
        public bool devolucion { get; set; }
    }
}
