//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_pvf
    {
        public int id_folio { get; set; }
        public int cantidad { get; set; }
        public string modelo { get; set; }
        public string descripcion { get; set; }
        public double precio { get; set; }
        public double total { get; set; }
        public string codigob { get; set; }
        public int pzasxpaq { get; set; }
        public int pzastotales { get; set; }
        public bool eliminar { get; set; }
    }
}
