//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public string Modelo { get; set; }
        public string Descripcion { get; set; }
        public int pzasxpaq { get; set; }
        public double l1 { get; set; }
        public double l2 { get; set; }
        public double l3 { get; set; }
        public bool t03 { get; set; }
        public bool t05 { get; set; }
        public bool t07 { get; set; }
        public bool t09 { get; set; }
        public bool t11 { get; set; }
        public bool t13 { get; set; }
        public bool tch { get; set; }
        public bool tm { get; set; }
        public bool tg { get; set; }
        public string codigob { get; set; }
        public int t03cant { get; set; }
        public int t05cant { get; set; }
        public int t07cant { get; set; }
        public int t09cant { get; set; }
        public int t11cant { get; set; }
        public int t13cant { get; set; }
        public int tchcant { get; set; }
        public int tmcant { get; set; }
        public int tgcant { get; set; }
        public double existencia { get; set; }
        public double compras { get; set; }
        public double ventas { get; set; }
        public double transito { get; set; }
        public double traspasos { get; set; }
        public double final { get; set; }
        public double existencia_saldos { get; set; }
        public int foto1 { get; set; }
        public int foto2 { get; set; }
        public int foto3 { get; set; }
        public int Pzasprod { get; set; }
        public double costo_historico { get; set; }
        public double costo_promedio { get; set; }
        public double costo_actual { get; set; }
        public string maquilero { get; set; }
        public System.DateTime fecha { get; set; }
        public double descuento { get; set; }
        public int apartado { get; set; }
        public bool corrida { get; set; }
        public sbyte liberado { get; set; }
    }
}
