//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedoresmp
    {
        public int idproveedor { get; set; }
        public string nombre { get; set; }
        public string nombreabreviado { get; set; }
        public string contacto { get; set; }
        public string oficina { get; set; }
        public string radio { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string diasdecredito { get; set; }
        public System.DateTime fecha { get; set; }
        public string direccion { get; set; }
        public string colonia { get; set; }
        public string poblacion { get; set; }
        public string cp { get; set; }
        public string rfc { get; set; }
        public string giro { get; set; }
        public string movil { get; set; }
        public string web { get; set; }
        public string tipo { get; set; }
        public string oficinav { get; set; }
        public string extov { get; set; }
        public string extfv { get; set; }
        public string extoc { get; set; }
        public string contactov { get; set; }
        public string emailv { get; set; }
    }
}
