//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibosch
    {
        public int idrecibo { get; set; }
        public string banco { get; set; }
        public string titular { get; set; }
        public string noch { get; set; }
        public double importe { get; set; }
        public System.DateTime vence { get; set; }
        public int idcliente { get; set; }
        public bool devolucion { get; set; }
    }
}
