//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public int indexs { get; set; }
        public int indexc { get; set; }
        public string nombre { get; set; }
        public string domicilio { get; set; }
        public string poblacion { get; set; }
        public string cp { get; set; }
        public string estado { get; set; }
        public string contacto { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
    }
}
