//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frida.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int index { get; set; }
        public string Vista { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
        public int id_agente_venta { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string poblacion { get; set; }
        public int codigo_postal { get; set; }
    }
}
