//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FridaExpo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int Index { get; set; }
        public string Clientef { get; set; }
        public bool Av { get; set; }
        public string DomicilioF { get; set; }
        public string coloniaF { get; set; }
        public string cpF { get; set; }
        public string Plazo_Credito { get; set; }
        public double Limite_Credito { get; set; }
        public string PoblacionF { get; set; }
        public string RfcF { get; set; }
        public string CurpF { get; set; }
        public string TelF { get; set; }
        public string radiof { get; set; }
        public string ContactoF { get; set; }
        public string ContactoE { get; set; }
        public string DomicilioE { get; set; }
        public string PoblacionE { get; set; }
        public string TelE { get; set; }
        public string PaqE { get; set; }
        public string FaxE { get; set; }
        public string EmailE { get; set; }
        public string WebE { get; set; }
        public string RecibeE { get; set; }
        public string ContactoT { get; set; }
        public string DomicilioT { get; set; }
        public string PoblacionT { get; set; }
        public string TelT { get; set; }
        public string FaxT { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaE { get; set; }
        public string estado { get; set; }
        public string agente { get; set; }
        public string movilf { get; set; }
        public int id_agente_venta { get; set; }
        public string status_solicitud { get; set; }
        public int politica_descuento { get; set; }
    }
}
