//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FridaExpo.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitantes
    {
        public int idVisitante { get; set; }
        public string nombreCliente { get; set; }
        public string nombreNegocio { get; set; }
        public string domicilio { get; set; }
        public string noExt { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public string estado { get; set; }
        public string tel { get; set; }
        public string cel { get; set; }
        public string celDos { get; set; }
        public string email { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int folioVisita { get; set; }
        public int idCliente { get; set; }
    }
}
